---
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: google/cloud-sdk
        tag: alpine
    inputs:
      - name: infrastructure-code
    run:
      dir: infrastructure-code
      path: /bin/sh
      args:
        - ci/tasks/build.sh
    