---
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: ashwinisoni2206/custom-image
        tag: latest
    inputs:
      - name: infrastructure-code
    run:
      dir: infrastructure-code
      path: /bin/sh
      args:
        - ci/tasks/validate.sh
    