---
    # repository and branch of the infrastructure code
    git_repo_infra_https: https://github.com/ashwini2206soni/tts-cloudrun.git
    git_branch_infra: master
    ## Teams
    teams_connector_url: ((teams_connector.url))
    # Terraform variables
    tf_provider_gcp_credentials: ((credentials))



    